FROM fedora-minimal:latest 
ARG INSTALLER_URL_BASE="https://download.nextcloud.com/server/releases"
ARG NEXTCLOUD_RELEASE="latest"

ENV \
	PUID=1000 \
	PGID=1000 \
	NEXTCLOUD_RUNTIME_USER=nextcloud \
	NEXTCLOUD_DB_TYPE=mysql \
	NEXTCLOUD_DB_HOST=mariadb-server \
	NEXTCLOUD_DB_DATABASE=nextcloud \
	NEXTCLOUD_DB_USER=nextcloud \
	NEXTCLOUD_DB_PASSWORD=nextcloud \
	NEXTCLOUD_DOMAIN=l4u.sytes.net \
	NEXTCLOUD_INSTANCE_ID=lera \
	NEXTCLOUD_SECRET=lera \
	NEXTCLOUD_SALT=lera \
	TZ=America/Recife \
	LANG=pt_BR.UTF-8 \
	HTTP_PORT=9090

RUN \
	#	--mount=type=cache,target=/var/cache \
	echo "SELINUX=disabled" > /etc/selinux/config && \
	dnf install --assumeyes \
	ffmpeg-free \
	php-pear-Net-Curl \
	php-pdo php-mysqlnd \
	php-mbstring \
	php-pear-XML-Parser php-xml php-pecl-xmlrpc \
	php-gd \
	php-mbstring \
	php-pecl-zip \
	php-intl \
	php-sodium php-pecl-mcrypt php-pear-Crypt-Blowfish \
	php-pear-Cache-Lite php-pecl-apcu php-pecl-memcached php-pecl-redis6 \
	php-pecl-imagick \
	php-ldap php-smbclient \
	php-pear-Mail php-pear-Net-IMAP php-pear-Net-SMTP \
	php-pecl-oauth php-pecl-pspell \
	php-seld-phar-utils \
	libreoffice libreoffice-langpack-pt-BR \
	php-fpm nginx &&\
	dnf clean all &&\
	groupadd --gid $PGID $USER &&\
	useradd --uid $PUID --gid $PGID --home /app --create-home $USER &&\
	curl -fsSL ${INSTALLER_URL_BASE}/${NEXTCLOUD_RELEASE}.tar.bz2 | \
	tar xvfj - --strip-components=1 -C /app && \
	mkdir /data &&\
	chown -R $PUID:$PGID /app /data

COPY <<EOF /app/config/config.php
<?php
$CONFIG = array (
  'instanceid' => $_ENV['NEXTCLOUD_INSTANCE_ID'],
  'passwordsalt' => $_ENV['NEXTCLOUD_SALT'],
  'secret' => $_ENV['NEXTCLOUD_SECRET'],
  'trusted_domains' => 
  array (
    0 => $_ENV['NEXTCLOUD_DOMAIN'],
    1 => 'localhost',
    2 => '127.0.0.1',
    3 => '[::1]',
  ),
  'datadirectory' => '/app/data',
  'dbtype' => $_ENV['NEXTCLOUD_DB_TYPE'],
  'version' => '26.0.0.0',
  'overwrite.cli.url' => 'http://'.$_ENV['NEXTCLOUD_DOMAIN'],
  'dbname' => $_ENV['NEXTCLOUD_DB_DATABASE'],
  'dbhost' => $_ENV['NEXTCLOUD_DB_HOST'],
  'dbport' => '',	
  'dbtableprefix' => 'oc_',
  'dbuser' => $_ENV['NEXTCLOUD_DB_USER'],
  'dbpassword' => $_ENV['NEXTCLOUD_DB_PASSWORD'],
  'installed' => true,
);
EOF


