ARG BASE_IMAGE=alpine:3.20
    
FROM $BASE_IMAGE AS build

ENV MINECRAFT_SERVER_URL=https://piston-data.mojang.com/v1/objects/4707d00eb834b446575d89a61a11b5d548d8c001/server.jar

RUN addgroup --gid 333 minecraft

RUN adduser --gecos 'Minecraft Server' \
    --home /app \
    --shell /dev/null \
    --ingroup minecraft \
    --disabled-password \
    --no-create-home \
    --uid 333 \
    minecraft

RUN mkdir -p /app /data

RUN chown minecraft:minecraft -R /app /data

RUN apk add --no-cache openjdk21-jre-headless

USER minecraft:minecraft
    
ADD --chown=minecraft:minecraft \
    --chmod=440 \
    --checksum=sha256:1066970b09e9c671844572291c4a871cc1ac2b85838bf7004fa0e778e10f1358 \
    $MINECRAFT_SERVER_URL /app/server.jar
    
ADD --chown=minecraft:minecraft \
    --chmod=540 \
    startup.sh /app/startup
##

FROM build AS prod

LABEL AUTHOR Laudivan Almeida
LABEL EMAIL laudivan@live.com
LABEL DESCRIPTION Minecraft Server Template \
    for me and my kids

ENV \
    JAVA_MEMORY_START=1024M\
    JAVA_MEMORY=1024M\
    SERVER_ID="LERA's Minecraft Vanilla Server"\
    BONUS_CHEST=false\
    SAFE_MODE=false\
    EULA=false

VOLUME /data

WORKDIR /data

EXPOSE 25565

ENTRYPOINT [ "/app/startup" ]