FROM registry.fedoraproject.org/fedora-toolbox:42 AS fedora-lau-toolbox

ARG NAME=fedora-lau-toolbox
ARG VERSION=42
LABEL com.github.containers.toolbox="true" \
      com.redhat.component="$NAME" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox(1) command" \
      summary="Image for creating Fedora Toolbx containers" \
      maintainer="Laudivan Almeida <lau@hanuky.space>"

COPY <<EOT /etc/profile.d/aliases.sh
alias dnf="sudo dnf --assumeyes"
alias podman="podman-remote --url \"unix:///run/user/$UID/podman/podman.sock\""
EOT

RUN dnf --refresh --assumeyes install \
        zsh.x86_64 kakoune.x86_64 fzf.x86_64 \
	    yt-dlp.noarch yt-dlp-bash-completion.noarch yt-dlp-zsh-completion.noarch\
	    tmux.x86_64 xpanes.noarch tmux-top.x86_64\
	    ncdu.x86_64 btop.x86_64 fastfetch.x86_64 \
	    zsh-autosuggestions.noarch \
	    vim-enhanced.x86_64 \
	    awesome-vim-colorschemes.noarch \
	    vim-commentary.noarch \
	    vim-devicons.noarch \
	    vim-filesystem.noarch \
	    vim-nerdtree.noarch \
	    vim-syntastic.noarch \
	    vim-syntastic-sh.noarch \
	    vim-syntastic-zsh.noarch \
	    vim-syntastic-vim.noarch \
	    vim-taglist.noarch \
	    flatpak-spawn.x86_64 \
	    glibc-langpack-cmn.x86_64 \
	    glibc-langpack-de.x86_64 \
	    glibc-langpack-en.x86_64 \
	    glibc-langpack-es.x86_64 \
	    glibc-langpack-he.x86_64 \
	    glibc-langpack-pt.x86_64 \
	    glibc-langpack-zh.x86_64 \
	    util-linux.x86_64 \
	    util-linux-i18n.x86_64 \
	    ncurses.x86_64 \
	    sudo.x86_64 \
	    podman-remote && \
	dnf clean all
